/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/account-management': RouteRecordInfo<'/account-management', '/account-management', Record<never, never>, Record<never, never>>,
    '/api-management': RouteRecordInfo<'/api-management', '/api-management', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/strategy/new': RouteRecordInfo<'/strategy/new', '/strategy/new', Record<never, never>, Record<never, never>>,
    '/trading-history': RouteRecordInfo<'/trading-history', '/trading-history', Record<never, never>, Record<never, never>>,
  }
}
